# Nombre de la aplicacion
spring.application.name=tickets

# Configuracion de conexion a base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tickets
spring.datasource.username=postgres
spring.datasource.password=ingesoftware
spring.datasource.driver-class-name=org.postgresql.Driver
server.address=0.0.0.0

# Configuracion de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Estrategia de creacion de tablas
# update: Actualiza la BD sin borrar datos
# create: Crea tablas desde cero (borra todo)
# create-drop: Igual que create pero las borra al cerrar
# none: No modifica la BD
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion JWT
security.jwt.access-secret=claveultrasecretaticketsingesoftwareaccess2026
security.jwt.refresh-secret=claveultrasecretaticketsingesoftwarerefresh2026
security.jwt.recovery-secret=claveultrasecretaticketsingesoftwarerecuperacion2026

# Duracion de tokens en milisegundos
security.jwt.access-expiration-ms=3600000
security.jwt.refresh-expiration-ms=604800000
security.jwt.recovery-expiration-ms=900000
